### ISSUE TITLE
Browser back button issues new request back to server since version 4.0.25+ instead of use browser cached version

### ISSUE THREAD

**Issue by MaximMartel** [wet-boew/cdts-sgdc#100]
Moved from GCCode: https://gccode.ssc-spc.gc.ca/sgdc-cdts/sgdc-cdts/issues/3

Hanwen Cai created the issue

We experienced an issue with the browser back button when trying to upgrade to CDTS version 4.0.25+. Our web app let user enter search criteria in a web form that issues a POST request back to our server which then returns a search result page with a list of items and the users can click on each item to view details. Currently, when a user clicks the browser back button on the item details page, the browser will show the cached version of the search result. However, when I simply update the CDTS version to point to 4.0.27, whenever we click on the back button from the item details page, it issues a GET request back to the server and resulted an error 500 page due to the absence of the search form information. This issue happens in IE and Chrome when javascript is enabled. Somewhere in the template javascript causes the browser back button to behave differently than before. Could you please help identify the cause of the issue and how to rectify it?

**Comment by MaximMartel** [comment]
@shawnthompson commented:

Hello @hcai, would you have a working example of this problem?

CDTS wouldn't have an affect on the back button. Could be a WET problem.

I tried to find something in WET but all I found was that they added URL mapping functionality, I'm wondering if this has any effect on the back button?

http://wet-boew.github.io/themes-dist/GCWeb/demos/urlmapping/ajax-en.html

**Comment by MaximMartel** [comment]
Hanwen Cai commented: 

Hello @ShawnThompson,

I just put an example on our Dev server temporarily. You could access it by URL https://health-products-dev.hres.ca/dpd-bdpp/index-eng.jsp

You could also compare the difference with our current PROD version https://health-products.canada.ca/dpd-bdpp/index-eng.jsp

The Dev version is simply an upgrade to CDTS 4.0.27 while the PROD version is 4.0.24 with no other code changes. When you search, you could use the "search by criteria", select any status (ex. Approved) and enter a company name (ex. Pfizer) and click on "Search". On the search result page, you click on a link to a product and then click on the back button. The Dev version will not go back to the search result page but the PROD version will. Since this application handles the error 500 more gracefully than out other apps, you see that it's returned back to the search page. If you turn off the Javascript for the Dev version or use Firefox instead of IE or Chrome, you could see the search result page by clicking on the back button. Somewhere in the Javascript after version 4.0.25 forced the back button to issue another trip back to the server instead of using the version cached by the browser.

I hope this example will help you better understanding this issue. BTW, do you have an idea how long you would need the example for? We may need the Dev server later on for our client to test a future release.

Thank you,

Hanwen

**Comment by MaximMartel** [comment]
@shawnthompson comment:

@hcai, Thanks I'll take a look at it sometime this week. Hopefully we can find the problem.

Stay tuned!

**Comment by MaximMartel** [comment]
Hanwen Cai commented:

Hello @ShawnThompson

Have you got chance to look at the this and figure out what part of the JavaScript causes the issue? If not, do you have any idea how long you need it as we will have to use our Dev server to test a future release later on. BTW, I noticed our apps on the Dev server sometimes gives 504 timeout. In case you get that error, you can send me an email and I'll simply do a re-deploy to fix it.

Thank you,

Hanwen

**Comment by MaximMartel** [comment]
Hanwen Cai commented: 

Any updates on this? We have to release a new version of our web application and the previous example is no longer available now.

**Comment by MaximMartel** [comment]
Eric Gagon-Munger comment:

Hi @hcai, do you think we can access to the dev again? I have tested in my side and the back button is working well on IE and Firefox. I would like to see on your dev server to be sure.

Regards, Eric

**Comment by MaximMartel** [comment]
Hanwen Cai commented:

Hi @kawish7, sorry, we published a new version on our dev server for our client to test and we have to fix the back button issue in our Java code to call and search the database again. The page no longer throws an error but if you use any of the network traffic tools, you may see that when you use back or forward button, it's not using the cached POST request, but issued a new GET for the url.

**Comment by ipaksc** [comment]
Hi @hcai. Is this still happening?

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by ahmad-shahid** [comment]
Last updated in 2018: "The page no longer throws an error." Closing issue.
