### ISSUE TITLE
Screen reader not announcing errors on Web forms

### ISSUE THREAD

**Issue by bsw2112** [wet-boew/cdts-sgdc#1284]
When some required fields are left empty on a form and I press submit the screen reader in JAWS does not automatically read 
the heading: The form could not be submitted because 2 errors were found.

I must first press the arrow down key once at which point it will read it. If should read it as soon as the form is submitted.
It works correctly here https://wet-boew.github.io/wet-boew/demos/formvalid/formvalid-en.html but not when WET is loaded via CTDS
Thanks

borys.wawryn@sac-isc.gc.ca

**Comment by ahmad-shahid** [comment]
Hello, I'll investigate this. Do you have a link to a site that has this issue?

**Comment by bsw2112** [comment]
Hello Ahmad

Here is a sample: https://www.sac-isc.gc.ca/eng/1585664064807/1585678941114

I am running JAWS version 2023.2311.34
When I leave the two fields empty and press submit I see the error message but I need to press the arrow down key once to hear the heading: The form could not be submitted because 2 errors were found

However when I go to the WET examples here: https://wet-boew.github.io/wet-boew/demos/formvalid/formvalid-en.html#wb-cont
The screen reader reads the error out right away. "The form could not be submitted because 9 errors were found."

This is affecting all our Internal forms.

Thanks
borys.wawryn@sac-isc.gc.ca

**Comment by ahmad-shahid** [comment]
Thank you

**Comment by bsw2112** [comment]
Hi Ahmad

I have sent the links to our visually impaired employee to review each of the three links. As soon as I hear back I will reply with the results

Thanks!

**Comment by bsw2112** [comment]
Hi Ahmad

From what I told the links you provided have not rectified the issue
I had a visually impaired user test it and one of the developers too
The dev provided a video recording of what he hears - https://www.youtube.com/watch?v=cR26Pw4GV24

The dev created a hack to fix this for our Intranet so if you wanted to know more about what he did please let me know

**Comment by ELefebvreSAC** [comment]
The fix I put in was moving the icon INTO the H2 as it is in base WET.

We only implemented it on ALERT-DANGER as it was the most urgent one for screen readers hoping it would get fixed at CDTS but here is the quick fix we added to out custon css file.

   /* Eric - 2024-05-30  */
    .alert-danger::before {
        all: unset !important;
    }

    .alert-danger>:first-child:before {
        color: #d3080c;
        content: "\e101";
        margin-top: 3px;
        margin-left: -1.7em;
    }

This moves the icon into the H2.
![image](https://github.com/user-attachments/assets/026824c3-4a29-492b-b356-c600f3419ef8)

In CDTS it appears that you have moved the ICONS (exclamation mark for example) outside the H2.

CDTS
![image](https://github.com/user-attachments/assets/d8d64356-0194-4ff2-929d-2cafe3f98ba6)

BASE WET
![image](https://github.com/user-attachments/assets/ba9dd8f7-f504-4bb9-97fc-a1d6ef2df687)

I then positioned the icon so it looks like CDTS VS base WET.

CDT look
![image](https://github.com/user-attachments/assets/d00dc503-c642-4ee3-a372-8accd6aa4b1e)

WET LOOK
![image](https://github.com/user-attachments/assets/f4b57d03-aed3-4c08-b8b5-2dedb1cfe98b)

MY LOOK
![image](https://github.com/user-attachments/assets/72297b14-ec1f-46e4-81cf-e83601f2466e)

**Comment by bsw2112** [comment]
Hello

Do you have any questions on what we provided? Any update on when this may be fixed?

**Comment by ahmad-shahid** [comment]
Apologies for the late response. Yes, this should be fixed as part of our next release. Due to the holidays, our next release should happen early next month.

**Comment by bsw2112** [comment]
Great thanks

We will check a few weeks into January

Regards
bsw2112

**Comment by bsw2112** [comment]
Hello Ahmad
Any updates on this? I checked just now and it's still not working. Has the fix been released?
Thanks

Borys Wawryn

**Comment by ahmad-shahid** [comment]
Hello, in order to resolve this, I was trying to find a permanent solution instead of a quick fix. In doing so, I realized that the WET documentation you provided uses the old WET version (the warnings have a background colour). The new version of WET has updated these warning messages: https://wet-boew.github.io/GCWeb/common/alert/alerts-en.html

If you use the updated WET version and add a form to a page (without any CDTS), you will run into the exact same issue with the icon being outside of the h2. This is a WET issue and not a CDTS one. 

In this case, I would suggest opening an issue in the WET repo: https://github.com/wet-boew/wet-boew/issues and continue using the quick fix that you have until WET resolves this.

**Comment by bsw2112** [comment]
Ok thanks I see what you mean and can confirm it's not working on the link: https://wet-boew.github.io/gcweb-compiled-demos/wetboew-demos/formvalid/formvalid-en.html

It's too bad when I Google "Wet Examples" the first hit is https://wet-boew.github.io/wet-boew/index-en.html from which I linked to Examples then the form validation - https://wet-boew.github.io/wet-boew/demos/formvalid/formvalid-en.html 

When I view sourced the referenced wet-boew.js file in https://wet-boew.github.io/wet-boew/demos/formvalid/formvalid-en.html

the date modified in the file was

/*!
 * Web Experience Toolkit (WET) / Boîte à outils de l'expérience Web (BOEW)
 * wet-boew.github.io/wet-boew/License-en.html / wet-boew.github.io/wet-boew/Licence-fr.html
 * v4.0.84 - 2025-01-14
*

which we assumed meant we were looking at the latest WET (even thought the theme is different. At the time was a bit older but still not that old)

In any case, we will open the ticket with WET. Thanks for your help Ahmad

Borys Wawryn
